import type { Metadata } from "next";
import "./globals.css";
import { Layout } from "@/components/Layout";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Layout>
        <body>{children}</body>
      </Layout>
      <Toaster richColors position="top-right" />
    </html>
  );
}
